# -*- coding: utf-8 -*-
"""week5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKM7ASscVTmWBQD66Tv14fvjJ66rB6IB
"""

# Week 5 in-class acitvity, Data Transformation 
import pandas as pd
import numpy as np
import re

# Part A
books = pd.read_csv('drive/MyDrive/books.csv')
books.drop(columns=[
                   'Edition Statement',
                   'Corporate Author',
                   'Corporate Contributors',
                   'Former owner',
                   'Engraver',
                   'Issuance type',
                   'Shelfmarks'
                   ])

books2 = pd.read_csv('drive/MyDrive/books.csv', usecols=[    
  'Identifier',
  'Place of Publication',
  'Date of Publication',
  'Publisher',
  'Title',
  'Author',
  'Contributors',
  'Flickr URL'                                  
])

# Part B
def fixDate(date):
  date = str(date)
  match = re.match('^\[(\d{4})\]$', date)
  match2 = re.match('(\d{2})(\d{2}),\D*(\d{2})?(\d{2})', date)
  match3 = re.match('\[?\d{4}\?\]?', date)
  match4 = re.search('\d{4}', date)

  if match:
    return match.group(1)
  elif match2:
    return match2.group(1)+match2.group(4)
  elif match3 or (date == 'nan'):
    return np.nan
  elif match4:
    return match4.group(0)
  else:
    return np.nan

books['Date of Publication'] = books['Date of Publication'].apply(lambda s: fixDate(s))

books['Date of Publication'] = pd.to_numeric(books['Date of Publication'])

# Part C
uni_data = pd.DataFrame(columns=['College','City','State'])

def createTable(row):
  state = np.nan
  city = np.nan
  uni = np.nan
  s = re.search('(\w*)\[edit\]', row)
  if s:
    state = s.group(1)
  cu = re.search('(\w*)\W\((.*)\)', row)
  if cu:
    city = cu.group(1)
    uni = cu.group(2)
  
  uni_data.loc[len(uni_data)] = [uni, city, state]
  
universities = pd.read_table('./drive/MyDrive/uniplaces.txt',names=['agg'])
universities.applymap(createTable)
uni_data['State'] = uni_data['State'].ffill()
uni_data = uni_data.dropna()

# Part D

import re

x = re.search('(\d{2})(\d{2}),\D*(\d{2})?(\d{2})','1879 [1878]')
match = re.match('^\[(\d{4})\]$', '1879 [1878]')
match3 = re.match('\[?\d{4}\?\]?', '1879 [1878]')
match4 = re.search('(\d{4})', '1879 [1878]')
print(match4.group(1))